// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewVideo struct {
	Title  string `json:"title" bson:"title"`
	URL    string `json:"url" bson:"url"`
	UserID string `json:"userID" bson:"userID"`
}

type User struct {
	ID   string `json:"id" bson:"_id"`
	Name string `json:"name" bson:"name"`
}

type Video struct {
	ID     string `json:"id" bson:"_id"`
	Title  string `json:"title" bson:"title"`
	URL    string `json:"url" bson:"url"`
	Author *User  `json:"author" bson:"author"`
}
